### PR TITLE
Add Connection Pool Support

### PR DESCRIPTION
**Pull request by leopeng1995**
I added connection pool from urllib3 support to cent.

### CODE REVIEW

**Comment by FZambia** [comment]
Hello @leopeng1995 , does adding Pool solve any specific problem you came across?

**Comment by leopeng1995** [comment]
Actually, I regard http connection pool as a enhancement. Now the sdk (cent) creates a http request per server backend push, that consumes many... Ohoooo, I gotcha. Even if I add connection pool, it also will creates a http request per push as these requests cannot share the same header!!! I originally hope save the  connection time and tons of same headers consumption.

**Comment by FZambia** [comment]
Connection pool is a reuse of TCP connection to host, so it should improve situation a bit making less TCP handshakes. But it won't help you with headers if this was your task.

Btw there is a better way to add connection pooling support as far as I understand - just using Session from `requests` and [HTTPAdapter](http://docs.python-requests.org/en/latest/api/#requests.adapters.HTTPAdapter):

```
import requests

sess = requests.Session()

adapter = requests.adapters.HTTPAdapter(pool_connections=5, pool_maxsize=5)
sess.mount('http://', adapter)
sess.mount('https://', adapter)

resp = sess.post("http://localhost:8000/api/")
```

This way we don't introduce new dependency as `urllib3` is already part of `requests`. But the question is do we really need it in `cent`?

**Comment by FZambia** [comment]
We can make all requests to Centrifugo  via `requests.Session()` and add a `session` kwarg to Client `__init__` method to pass user-defined session (for example one with configured adapter I showed above) - I think this could be pretty elegant then.

**Comment by leopeng1995** [comment]
So if we need to improve speed/concurrency to push messages to Centrifugo server, the only method is scaling out Centrifugo with Redis cluster? Are there another way like enhancing the backend sdk?
The solution about Session sounds good. :-)

**Comment by FZambia** [comment]
> So if we need to improve speed/concurrency to push messages to Centrifugo server, the only method is scaling out Centrifugo with Redis cluster? Are there another way like enhancing the backend sdk?

In other way you want to push more messages from backend to Centrifugo? If yes, using session can help a bit I think if you will use the same client instance to publish messages.

How many messages you are planning to publish to Centrifugo? And what is on your backend - Django, Flask or sth else?

**Comment by leopeng1995** [comment]
Flask. Are you mean Singleton?

**Comment by leopeng1995** [comment]
Actually in this moment our application just comes online about one month. So the quantity of messages still is under control. Do you mean there are some benchmark about Centrifugo?

**Comment by FZambia** [comment]
Yep, something like singleton - i.e. if you create client instance on every push you can improve it making client instance global and reuse it. If we add session it will be even better. But not significantly I suppose.

Have you already faced with problem?

**Comment by FZambia** [comment]
@leopeng1995 just released 2.1.0 that uses requests.Session: see [changelog](https://github.com/centrifugal/cent/blob/master/CHANGELOG.md#210) - this should speed up things if using shared `Client` instance

**Comment by leopeng1995** [comment]
Thanks for @FZambia . Do we need a benchmark between 2.0.0 and 2.1.0 ?

**Comment by FZambia** [comment]
@leopeng1995 I made a rude bench when added Session - making many sequential requests to Centrifugo in one thread. Version with session was 30% faster. It can vary depending on how you are using `cent`. You can make your own if you want and share.

**Pull request closed without merging**
