### PR TITLE
Make it async

### PR DESCRIPTION
**Pull request by oleynikandrey**

### CODE REVIEW

**Comment by FZambia** [comment]
@oleynikandrey hello! Looks like this is not backwards compatible.

I suppose we can drop Python 2.6 support, but I'd like to keep compatibility with 2.7. 

And what if someone uses `cent` in non-async environment like Django?

**Comment by FZambia** [comment]
Thanks for the tip about wrong key used `history` method!

**Comment by FZambia** [comment]
@oleynikandrey what do you think? Maybe this should me another project? I can add a link to your Github account and async client into docs

**Comment by oleynikandrey** [comment]
@FZambia, sorry I've opened this pull request accidentally)
This definitely should be another project. But It won't be compatible with python 2.7, because of aiohttp  require Python 3.5.3+.
I'll create separate project and send link.

**Pull request closed without merging**
